Ams 5 full registration
alex-parkhamovich/amsmpc pull request #7
Opened 2017-04-21 09:18 UTC by alex-parkhamovich

Full registration with 2 steps, change controllers actions to defaults show/update and etc.

2017-04-21 15:33 UTC, tuwukee requested changes

2017-04-21 15:33 UTC, tuwukee commented on app/controllers/doctor_admin/after_signup_controller.rb
> +    if @personal.update_attributes(doctor_personal_params)
Why don't you handle errors on update?

2017-04-21 15:33 UTC, tuwukee commented on app/controllers/patient_admin/after_signup_controller.rb
> +  def update
A lot of code duplication, is it possible to inherit it from some base controller with list of the default actions or store shred methods in the concerns?

2017-04-21 15:33 UTC, tuwukee commented on app/controllers/patient_admin/after_signup_controller.rb
> +    @personal = current_user.patient_personal
Where is the rspec tests? >:)

2017-04-22 08:11 UTC, alex-parkhamovich commented on app/controllers/doctor_admin/after_signup_controller.rb
> +    if @personal.update_attributes(doctor_personal_params)
forgot it, i'll add it in next commit.

2017-04-22 08:12 UTC, alex-parkhamovich commented on app/controllers/patient_admin/after_signup_controller.rb
> +    @personal = current_user.patient_personal
in progress ^^

2017-05-04 13:57 UTC, tuwukee approved these changes

2017-05-04 13:57 UTC, merged